# server config
server:
  servlet:    
    session: 
      timeout: 1800
  tomcat:
    accesslog:
      enabled: true
      directory: /log/sw/tomcat/crm 
      
# Spring Configure
spring:
  servlet:
      multipart:
        max-file-size: 10GB
        max-request-size: 10GB
  nas:
    path:   /NFS/crm/
    url:    https://files.ceragem.com/crm/
  jwt:
    secret: 1qaz@WSX
  datasource:
    # Pool
    hikari:
      connection-timeout: 120000
      maximum-pool-size: 20
      log-maximum-pool-size: 10
    log-driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    log-url: jdbc:log4jdbc:oracle:thin:@172.23.1.91:8122:DCRMDB
    log-username: crmown
    log-password: crmown

    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@172.23.1.91:8122:DCRMDB
    username: crmown
    password: crmown
  api:
    base-url: https://dev-api.ceragem.com
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwidXNlckNkIjoiU1lTVEVNIiwic3lzdGVtQ2QiOiJDUk0iLCJleHAiOjE5NjU5Njc3OTN9.JdcD_hAcfinlJk10jvYJ1_99QX5Lc9aG0VGQQ_yK8YE      
    url:
      token-url: /api/v1.0/token/CRM
      customer: /crm/v1.0/customer
      customer-contact: /crm/v1.0/customer-contact
      customer-bond: /crm/v1.0/customer-bond
      customer-black: /crm/v1.0/customer-black
      point: /crm/v1.0/point
      ctc-hist: /ctc/v1.0/history
      as-hist: /as/v1.0/history
      customer-memship: /crm/v1.0/membership
      sap: /sap/v1.0/pnt
    bos-url: https://mapone.ceragem.com/crm
      
  jade:
    token-url: https://cerahr.ceragem.com:9950/restful/getToken
    rest-url: https://cerahr.ceragem.com:9950/restful
    ceragem: 2011040
    ceragem-cns: 2011041
    p1-param: REFwWALk0KnxM8S55r5wAA==
    org-param: ZjH2yGNkSXC63TMeuSX5Hw==
    hr-param: 438MVz40Ca2tE2C+CR1RDQ== 
  sso:
    mode : true
  #https://ceragem.ncpworkplace.com/authn/oauthLogin?response_type=code&client_id=zEgB3stWau126Qf9SWHf&redirect_uri=https://cerahr.ceragem.com:9950/authNaver/oauth2callback
    auth-url: https://ceragem.ncpworkplace.com/authn/oauthLogin
    token-url: https://ceragem.ncpworkplace.com/authn/accessToken
    profile-url: https://ceragem.ncpworkplace.com/authn/userProfile
    logout-url: https://ceragem.ncpworkplace.com/authn/logoutProcess
    callback-url: http://dev-crm.ceragem.com/login/oauth
    client-id: zEgB3stWau126Qf9SWHf
    client-secret: He72CbdYrE
  bi:
    url : http://dev-bi.ceragem.com   
    server : GLCMAP01D
  mcast:
    host: 228.0.0.4
    service-port: 45564
    receiver-port: 5000
  eon:
    send:
      url : http://dev-ums.ceragem.com/weom/servlet/servlet.WSOMZ000CR
      user : crm_1
    barcode-url: http://dev-ums.ceragem.com/weom/app/mmsimg
  batch:
    host: ENC(fSiGKFwqZrw3OftT2biHyio8GKv6O1rF)
    port: ENC(iOz8Eiefnv03j9gBfP4T9w==)
    user: ENC(JexNKJUWQeJGcnAQdiRn/w==)
    password: ENC(u9UzgWkFhnRd8Bczxk2t6o0oiClFDbJT)    
    path: ENC(+56hj4tJQHhyvlRoQ5WpTSLzi81H7BQqe5ZHzuLuBMQEHG7GU3mXhaZ5Bn7OESXXScqOebp6DJU=)
# Log
logging:
  #  file: logs/application.log
  config: classpath:logback-dev.xml
  level:
    com.ceragem: DEBUG
    org.springframework.web: INFO
    
jasypt:
  encryptor:
    bean: jasyptStringEncryptor   
