spring:
  application:
    name: ceragem-crm-bo
  jwt:
    secret: 1qa@WS

server:
  port: 80
  tomcat:
    basedir: /appdata/tomcat/crm
    accesslog:
      directory: /log/sw/tomcat/crm/
      enabled: true
      file-date-format: .yyyy-MM-dd
      max-days: 30
      pattern: '%h %l %u %t "%r" %s %b %D'
      prefix: access
      rotate: true
      suffix: .log